### ISSUE TITLE
The boolean for IsUpDown is true when a control is OneShot.

### ISSUE THREAD

**Issue by otac0n** [DevDecoder/HIDDevices#10]
https://github.com/DevDecoder/HIDDevices/blob/f565ecca1a44b783d1b8fee0ff5cd3efd2a419ce/HIDDevices/Control.cs#L182C77-L182C84

**Comment by thargy** [comment]
Good spot @otac0n 

Sorry for the delay in fixing this; I had to install Visual Studio to get the usage table regeneration working (which turned out to be unnecessary).  I also had to update the NuGet API Key, and it's the middle of the night here.

I hope this resolves your issue, feel free to reopen if not.
